### PR TITLE
App level usage enhancements

### PR DESCRIPTION
**Pull request by jayeshpowar**
## Status*
Review and merge

## Features Completed/Bugs Fixed
NA

## Description
Improvised on the command line options to be provided. Fixed the issues observed during execution on different environments with different agents. 

## Dependencies/Deployment Notes*
NA

## Reproduce/Test
NA

## Screenshots*
NA

### CODE REVIEW

**Comment by zoetetal** [comment]
@jayeshpowar  can you include some screen shots and/or a bit more detail on what's being fixed?

**Comment by jayeshpowar** [comment]
@zoetetal 

- Changed the way in which the arguments are processed , especially the way in which new arguments can be added . New arguments can be added relatively easily and defaults can be set in an easier way, also the overriding arguments can be passed from command line .
- Non apm agents can be shown in a manner where each row corresponds to one hour rather than one column belonging to each hour ( sort of vertical table instead of horizontal ). Also there is an option to skip the overall aggregated application usage and show only tier usage .

screen shot 2016-09-16 at 9 52 04 am

screen shot 2016-09-16 at 10 01 29 am

- Some of the REST calls were broken as the application name wasn't in a proper manner also some of the urls contained slashes which weren't supported . Added encoding mechanism wherever applicable and switched to using id instead of name in other cases where it wasn't possible to encode the urls.

Apart from all this , fixed any minor issues which have showed up while executing the test runs.

**Comment by zoetetal** [comment]
@jayeshpowar this looks good. Do you have any more changes?

**Comment by jayeshpowar** [comment]
@zoetetal Most of the modifications are in place , i want to add a few more items however they can be added as part of separate branch.

**Comment by zoetetal** [comment]
Looks good.

**Pull request merged**
